---
title: "p8105_hw3_yy3421"
output: github_document
---

## Problem 1
Loading dataset:

```{r}
library(tidyverse)
library(ggridges)
library(patchwork)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
library(p8105.datasets)
data("instacart")

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

### Question 1:

Group by aisle:

```{r}
instacart_aisle = instacart |> 
  group_by(aisle)
```

```{r}
n_item_max = instacart_aisle |> 
  summarise(n_item=n()) |> 
  arrange(desc(n_item))
```

There are `r instacart_aisle |> summarize() |> nrow()` aisles. The most items are ordered from aisle "`r n_item_max$aisle[1]`" with `r n_item_max$n_item[1]` items.

### Question 2:
```{r}
n_item_max |> 
  filter(
    n_item > 10000
  ) |> 
  ggplot(aes(x= reorder(aisle, +n_item), y = n_item))+
  geom_point() +
  labs(
    y = "Aisle",
    x = "Number of Items",
    caption = "Number of Items for Each Aisle with More than 10,000 Items"
  )+
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
```

### Question 3:
```{r}
instacart_aisle |> 
  group_by(aisle, product_name) |> 
  filter(
      aisle == "baking ingredients" | aisle == "dog food care" | aisle == "packaged vegetables fruits"
    ) |> 
  summarize(n_product = n()) |> 
  arrange(desc(n_product)) |> 
  mutate(
    product_rank = min_rank(desc(n_product))
    ) |> 
  filter(product_rank < 4) 

```

### Question 4:
```{r}
instacart |> 
  group_by(order_dow, product_name) |> 
  filter(
    product_name == "Pink Lady Apples"| product_name == "Coffee Ice Cream"
  ) |> 
  summarize(
    mean_hour = mean(order_hour_of_day)
  ) |> 
  mutate(
    order_dow = order_dow +1
  ) |> 
  pivot_wider(
    names_from = product_name,
    values_from = mean_hour
  )
```

## Problem 2

Load data and clean:

```{r}
library(p8105.datasets)
data("brfss_smart2010")
```

```{r}
brfss_smart2010 = 
  brfss_smart2010 |> 
  janitor::clean_names() |> 
  filter(
    topic == "Overall Health",
    response == "Excellent"|response == "Very good"|response == "Good"|response == "Fair"|response == "Poor"
  ) |> 
  mutate(
    response = factor(response, levels = c("Excellent", "Very good", "Good", "Fair", "Poor"))
  ) |> 
  arrange(desc(response))
```

### Question 1:


```{r}
brfss_smart2010_state = 
  brfss_smart2010 |> 
  group_by(locationabbr, locationdesc) |> 
  tally()
```

## Question 2:

```{r}
brfss_smart2010 |> 
  filter(
    response == "Excellent"
  ) |> 
  select(year, locationabbr, data_value
  ) |> 
  group_by(locationabbr, year) |> 
  summarize(avg_data_value = mean(data_value, na.rm = TRUE)) |>
  ggplot(aes(
    x = year, 
    y = avg_data_value, 
    color = locationabbr,
    group = locationabbr))+
  geom_point()+
  geom_line()+
  labs(
    x = "Year",
    y = "Average Data Values",
    caption = "Change in Average Data Values from 2002 to 2010 for Each State"
  )
```


## Question 3:

```{r}
brfss_smart2010 |> 
  filter(
    locationabbr == "NY",
    year == 2006 | year == 2010
  ) |> 
  ggplot(
    aes(
      x = response, y = data_value, fill = response
    )
  )+
  geom_boxplot()+
  facet_grid(~year)+
  labs(
    x = "Response",
    y = "Data Value",
    caption = "Distribution of Data Value for Responses between 2006 and 2010"
  )
```


## Problem 3

Cleaning and merging the two csv:

```{r}
nhanes_accel = 
  read_csv("data/nhanes_accel.csv")

nhanes_covar = 
  read_csv("data/nhanes_covar.csv", skip = 4)

nhanes_df = 
  left_join(nhanes_covar, nhanes_accel, by = join_by(SEQN)) |> 
  janitor::clean_names()|> 
  filter(
    age>=21,
    is.na(bmi) == FALSE,
    is.na(education) == FALSE
  ) |> 
   mutate(
    sex = 
      case_match(
        sex,
        1 ~ "male",
        2 ~ "female"),
    sex = as.factor(sex),
    education =
      case_match(
        education,
        1 ~ "less than high school",
        2 ~ "high school equivalent",
        3 ~ "more than high school"),
    education = factor(education, levels = c("less than high school", "high school equivalent", "more than high school"))
   )
```


